---
title: "Plots"
output: html_document
---

```{r setup, include=FALSE}
# setwd("C:/Users/tomas/OneDrive/Documents/Studies/PW-IAD/Optymalizacja/Optimization-Lasso-CoordinateDescent/Optimization-Lasso-CoordinateDescent/")

knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
require(knitr)
source("plots.R")
source("CPU_plots.R")
```

```{r}
diabetes <- read.csv2("diabetes.csv", sep = ',', header = TRUE, stringsAsFactors = FALSE)
diabetes <- transform(diabetes, BMI = as.numeric(BMI))
diabetes <- transform(diabetes, DiabetesPedigreeFunction = as.numeric(DiabetesPedigreeFunction))

x <- as.matrix(diabetes %>% select(-c("Outcome")))
y <- as.vector(diabetes %>% select(c("Outcome")))
y <- unlist(y)
x[is.na(x)] <- 0
x <- x / norm(x, type="2") # Normalize 
start_beta <- rep(0,8)
```

# Iteration vs cost

```{r}
lambda <- 0.0000001
max_iters <- 1000 
# res <- gen_plots(X=x, Y=y, start_beta=rep(0, 8),
#                  lambda=0.0000001, max_iters=1000,
#                  lambda_list=seq(0.0000001, 1, by=0.00001))
iter_cost_plots <- gen_iter_cost_plots(X=x, Y=y, start_beta=start_beta,
                 lambda=lambda, max_iters=max_iters) # lambda_list=seq(0.01, 10, by=0.02)
```

```{r}
iter_cost_plots$iter_cost_plot_1
```

```{r}
iter_cost_plots$iter_cost_plot_2
```

```{r}
iter_cost_plots$iter_cost_plot_3
```

```{r}
iter_cost_plots$iter_cost_plot_4
```

```{r}
iter_cost_plots$iter_cost_plot_5
```

```{r}
iter_cost_plots$iter_cost_plot_m
```

# Own implementation: each coefficient separately

```{r}
separate_betas_res <- separate_betas_plot(X=x, Y=y, start_beta=start_beta, max_iters=max_iters, lambda_list=seq(0.01, 10, by=0.02))
```

```{r}
separate_betas_res
```


# Iteration vs change of norm2 of consecutive beta

```{r}
iter_coef_change_plot_res <- iter_coef_change_plot(X=x, Y=y, start_beta=start_beta,
                 lambda=lambda, max_iters=max_iters)
```

```{r}
iter_coef_change_plot_res$beta_change_plot_1
```

```{r}
iter_coef_change_plot_res$beta_change_plot_2
```

```{r}
iter_coef_change_plot_res$beta_change_plot_3
```

```{r}
iter_coef_change_plot_res$beta_change_plot_4
```


# CPU plots

```{r}
res_cpu <- gen_cpu_plots(
          start_beta=rep(0, ncol(x)),
          X=x,
          Y=y,
          lambda=lambda,
          max_iters=max_iters,
          how_many_rows_list=seq(10,nrow(x),50)
        )
```

## CPU time vs number of samples

```{r}
res_cpu$cpu_n_plot
```

## CPU time vs number of variables

```{r}
res_cpu$cpu_p_plot
```


# Generated dataset

```{r}
generate_data <- function(y, n_cols, prob, max_variance){
  x <- matrix(nrow = length(y),ncol = n_cols)
  
  for(i in 1:n_cols){
    x[,i] <- y + rnorm(n = length(y), mean = 0, sd = runif(1,0,max_variance))
  }
  x
}


y <- rbinom(1000, 1, prob = 0.3)
n_cols <- 1000
x <- generate_data(y, n_cols=50,prob = 0.3, max_variance = 100)
start_beta <- rep(0, ncol(x))
```

## CPU plots

```{r}
res_cpu <- gen_cpu_plots(
          start_beta=rep(0, ncol(x)),
          X=x,
          Y=y,
          lambda=lambda,
          max_iters=max_iters,
          how_many_rows_list=seq(10,nrow(x),50)
        )
```

### CPU time vs number of samples

```{r}
res_cpu$cpu_n_plot
```

### CPU time vs number of variables

```{r}
res_cpu$cpu_p_plot
```

## Iteration vs cost

```{r}
iter_cost_plots <- gen_iter_cost_plots(X=x, Y=y, start_beta=start_beta,
                 lambda=lambda, max_iters=max_iters) # lambda_list=seq(0.01, 10, by=0.02)
```

```{r}
iter_cost_plots$iter_cost_plot_1
```

```{r}
iter_cost_plots$iter_cost_plot_2
```

```{r}
iter_cost_plots$iter_cost_plot_3
```

```{r}
iter_cost_plots$iter_cost_plot_4
```

```{r}
iter_cost_plots$iter_cost_plot_5
```

```{r}
iter_cost_plots$iter_cost_plot_m
```
